version: 2.1

jobs:
  run-fmm:
    docker:
      - image: bempp/cl-dev-env:with-exafmm
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/bempp/bempp-cl.git
            cd bempp-cl
            python3 setup.py install
          name: Install Bempp
      - run:
          command: |
            mkdir output
            python run.py fmm
          name: Run code
  run-opencl:
    docker:
      - image: bempp/cl-dev-env:with-exafmm
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/bempp/bempp-cl.git
            cd bempp-cl
            python3 setup.py install
          name: Install Bempp
      - run:
          command: |
            mkdir output
            python run.py opencl
          name: Run code
  run-numba:
    docker:
      - image: bempp/cl-dev-env:with-exafmm
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/bempp/bempp-cl.git
            cd bempp-cl
            python3 setup.py install
          name: Install Bempp
      - run:
          command: |
            mkdir output
            python run.py numba
          name: Run code

workflows:
  main:
    jobs:
      - run-fmm
